version: "2"

services:
  wordpress:
    image: wordpress
    restart: always
    restart: always
    volumes:
      - ./html:/var/www/html
    ports: 
      - 8081:80
    environment:
      WORDPRESS_DB_PASSWORD: example
  
  mysql:
    image: mariadb
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example